spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javaBank
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql:
        show_sql:

server:
  error:
    whitelabel:
      enabled: false
    include-message: always
  port: 8080
